version: '3'

services:
  web:
    build:
      context: .
      dockerfile: wayback/Dockerfile
    command: wayback
    ports:
      - 8080:8080
    volumes:
        - ./wayback/config.yaml:/webarchive/config.yaml
        - collections:/webarchive/collections/
        - sources:/webarchive/sources/
    environment:
      INIT_COLLECTION: gathering-org

  # Container for use with scheduled crawl configurations.
  #
  # Does nothing by default, see readme for details on usage.
  crawler:
    image: webrecorder/browsertrix-crawler
    command: 'echo "Crawler exiting, no commands to run"'
    ports:
      - 9037:9037
    volumes:
        - ./browsertrix-crawler/configs:/app/configs
        - ./profiles:/crawls/profiles
        - collections:/crawls/collections

volumes:
  # Change to whatever local volume config is used for collections (if any)
  collections:
    driver_opts:
      type: none
      device: ${PWD}/collections
      o: bind
  sources:
