seeds:
  - url: https://www.gathering.org/tg22/
    include: www.gathering.org/(tg22|api)

collection: tg22

behaviors: autoscroll,autoplay,autofetch,siteSpecific
waitUntil: load,networkidle0
generateCDX: true
combineWARCs: true
saveState: always
workers: 2

# Make "live" crawling view available at 9037
newContext: window
screencastPort: 9037

warcinfo:
  operator: The Gathering
  hostname: gathering.org
